FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /mockollama ./cmd/mockollama

FROM alpine:latest
RUN apk --no-cache add wget
COPY --from=builder /mockollama /mockollama
EXPOSE 11434
ENTRYPOINT ["/mockollama"]
