package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/ollama-mesh/ollama-mesh/internal/cli"
)

// readme.go rewrites README.md's CLI table in place, between two marker
// comments. It fails loudly (non-zero exit, clear error) if the markers are
// missing - it must never silently append or guess a location to edit.

const (
	readmeBeginMarker = "<!-- BEGIN CLI TABLE -->"
	readmeEndMarker   = "<!-- END CLI TABLE -->"
)

// nonRegistryRows are real subcommands of the ollama-mesh binary that are
// NOT part of internal/cli's Command registry - "agent" and "bench" select
// an entirely different mode of the binary (Node Agent / benchmark tool,
// see main.go), and "uninstall" is handled by uninstall.go, not
// internal/cli. They still belong in the README's CLI table for a human
// reading "what can this binary do", so they're prepended by hand rather
// than derived - this is the one place gen-docs doesn't come purely from
// the registry, and it's the reason: these three deliberately live outside
// it.
var nonRegistryRows = [][2]string{
	{"ollama-mesh agent", "Run a Node Agent (node-local execution point for the mesh)"},
	{"ollama-mesh bench", "Benchmark warm-vs-cold first-token latency against a running mesh"},
	{"ollama-mesh uninstall [--purge]", "Remove the mesh's and/or Node Agent's service registration from this host"},
}

func generateReadmeTable(root *cli.Command) error {
	data, err := os.ReadFile("README.md")
	if err != nil {
		return err
	}
	content := string(data)

	beginIdx := strings.Index(content, readmeBeginMarker)
	endIdx := strings.Index(content, readmeEndMarker)
	if beginIdx == -1 || endIdx == -1 || endIdx < beginIdx {
		return fmt.Errorf("README.md is missing the %q/%q markers around its CLI table - "+
			"insert them once around the existing table before running gen-docs; refusing to "+
			"guess a location to edit", readmeBeginMarker, readmeEndMarker)
	}

	table := renderReadmeTable(root)
	newContent := content[:beginIdx] + readmeBeginMarker + "\n" +
		"<!-- Generated by `make docs` (cmd/gen-docs) from internal/cli's command registry - do not edit by hand. -->\n" +
		table + readmeEndMarker + content[endIdx+len(readmeEndMarker):]

	if newContent == content {
		return nil
	}
	return os.WriteFile("README.md", []byte(newContent), 0644)
}

func renderReadmeTable(root *cli.Command) string {
	var b strings.Builder
	b.WriteString("| Command | Purpose |\n")
	b.WriteString("|---|---|\n")
	fmt.Fprintf(&b, "| `%s` | Run the mesh server (default, no argument needed) |\n", root.Name)
	for _, row := range nonRegistryRows {
		fmt.Fprintf(&b, "| `%s` | %s |\n", row[0], row[1])
	}
	for _, c := range root.Sub {
		writeReadmeRows(&b, root, c, nil)
	}
	return b.String()
}

func writeReadmeRows(b *strings.Builder, root, c *cli.Command, pathPrefix []string) {
	path := append(append([]string{}, pathPrefix...), c.Name)
	name := root.Name + " " + strings.Join(path, " ") + argsSuffix(c.Args)

	purpose := c.Short
	if c.NeedsAuth {
		purpose += " (requires auth)"
	}
	if c.Hidden {
		purpose += " (hidden from `--help`; see `docs/cli.md`)"
	}
	fmt.Fprintf(b, "| `%s` | %s |\n", escapeMarkdownPipes(name), escapeMarkdownPipes(purpose))

	for _, sub := range c.Sub {
		writeReadmeRows(b, root, sub, path)
	}
}

func escapeMarkdownPipes(s string) string {
	return strings.ReplaceAll(s, "|", `\|`)
}
